style: github
template: CHANGELOG.tpl.md
info:
    title: CHANGELOG
    repository_url: https://github.com/maicol07/flarum-ext-sso
options:
    commits:
        filters:
            Type:
                - feat
                - update
                - perf
                - fix
                - fixed
                - revert
                - rename
                - refactor
                - style
                - docs
                - build
                - ci
                - chore
    commit_groups:
        sort_by: Custom
        title_order:
            - feat
            - update
            - perf
            - fix
            - fixed
            - revert
            - rename
            - refactor
            - style
            - docs
            - build
            - ci
            - chore
        title_maps:
            feat: âœ¨ Features
            fix: ğŸ› Bug Fixes
            fixed: ğŸ› Bug Fixes
            perf: âš¡ Performance Improvements
            docs: ğŸ“ Docs changes
            refactor: â™» Code Refactoring
            rename: ğŸšš Renamed
            revert: âª Reverted
            update: ğŸ”„ Updates
            build: ğŸ‘· Building scripts changes
            chore: Other changes
            style: ğŸ¨ Code styling
            ci: ğŸ‘· CI changes
    header:
        pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
        pattern_maps:
            - Type
            - Scope
            - Subject
    notes:
        keywords:
            - BREAKING CHANGE
            - ğŸ’¥
